username = input("Enter your username: ")
title1 = input("Enter the name of your 1st task: ")
title2 = input("Enter the name of your 2nd task: ")
title3 = input("Enter the name of your 3rd task: ")
content = input("Enter the content of your task: ")
status = input("Enter the status of your task: ")
created_date = input("Enter the created date in DD-MM format: ")
issue_date = input("Enter the issue date in DD-MM format: ")
titles_list = [title1, title2, title3]

print(f"The username of the person creating the task: {username}")
print(f"The titles of the task: {", ".join(titles_list)}")
print(f"The content or description of the task: {content}")
print(f"The current status of the task: {status}")
print(f"The date the task was created: {"-".join(created_date.split("-")[:2])}")
print(f"The date the task is issued: {"-".join(issue_date.split("-")[:2])}")
